app:
    hostname: go
    build: ./docker/app
    volumes:
        - "./log:/log"
    ports:
        - "80:80"
    links:
        - mysql

mysql:
    hostname: mysql
    image: mysql
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root